---
backend:
  host:
  port: 8000
easypick:
  host: 127.0.0.1
  port: 5000
  username: yourEasyStoreUsername
  password: yourEasyStorePassword
database:
  host: database
  database: database
  username: username
  password: password
trading:
  ajeossi: 2 #大叔費用(%)
  shippingFee: 7200 #國際運費
  exchangeRate: 40.9 #匯率
  tariff: 35 #關稅
  markup: 1.45 #定價倍率
  costs:
    - key: 包材
      value: 25
    - key: 運費
      value: 35
    - key: 手續費
      value: 20
    - key: 平台
      value: 15
    - key: 廣告
      value: 20
    - key: 首購
      value: 25
