backend:
    host: 127.0.0.1
    port: "8000"
easypick:
    host: 127.0.0.1
    port: "5000"
    username: yourEasyStoreUsername
    password: yourEasyStorePassword
database:
    host: 127.0.0.1
    database: daymood
    username: daymood
    password: daymooddev
trading:
    ajeossi: 2
    shippingFee: 7200
    exchangeRate: 40.9
    tariff: 35
    markup: 1.45
    costs:
        - key: 包材
          value: 25
        - key: 運費
          value: 35
        - key: 手續費
          value: 20
        - key: 平台
          value: 15
        - key: 廣告
          value: 20
        - key: 首購
          value: 25