Trading:
    Ajeossi: 3
    ShippingFee: 7300
    ExchangeRate: 40.9
    Tariff: 36
    Markup: 1.45
    Costs:
        - Key: 包材
          Value: 25
        - Key: 運費
          Value: 35
        - Key: 手續費
          Value: 20
        - Key: 平台
          Value: 15
        - Key: 廣告
          Value: 20
        - Key: 首購
          Value: 25
